import XCTest
@testable import GitaKit

/// Verifies the real bundled content (`gita.json`, generated by Tools/fetch-content) decodes and is
/// shaped as the app expects. This is the Phase 1 guard: if the resource is dropped from the package
/// or the schema drifts, these fail instead of the app silently falling back to the 5 samples.
final class ContentLoaderTests: XCTestCase {
    private let shlokas = ContentLoader().load()

    func testLoadsAllShlokas() {
        // The gita/gita dataset numbers the Gita as 701 shlokas (see Tools/fetch-content/README.md).
        XCTAssertEqual(shlokas.count, 701)
    }

    func testCoversAllEighteenChapters() {
        let chapters = Set(shlokas.map(\.chapter))
        XCTAssertEqual(chapters, Set(1...18))
    }

    func testEveryShlokaHasContent() {
        for s in shlokas {
            XCTAssertFalse(s.transliteration.isEmpty, "\(s.id) has empty transliteration")
            XCTAssertFalse(s.meaning.isEmpty, "\(s.id) has empty meaning")
        }
    }

    func testIDsAreUnique() {
        XCTAssertEqual(Set(shlokas.map(\.id)).count, shlokas.count)
    }

    func testKnownShlokaText() {
        let store = ContentStore(shlokas: shlokas)
        let bg247 = store.shloka(id: "2.47")
        XCTAssertEqual(bg247?.chapter, 2)
        XCTAssertEqual(bg247?.number, 47)
        // Swami Sivananda's translation (the chosen "meaning" — PRD §10.3).
        XCTAssertTrue(
            bg247?.meaning.hasPrefix("Your right is only to work") ?? false,
            "unexpected meaning for 2.47: \(bg247?.meaning ?? "nil")"
        )
        XCTAssertTrue(bg247?.transliteration.contains("karmaṇy") ?? false)
    }

    func testDidNotFallBackToSamples() {
        // The 5-item sample set must never be what ships; catch a missing/broken resource.
        XCTAssertNotEqual(shlokas, ContentStore.sampleShlokas)
    }
}
