import XCTest
@testable import GitaKit

/// Verifies the real bundled content (`gita.json`, generated by Tools/fetch-content) decodes and is
/// shaped as the app expects. This is the Phase 1 guard: if the resource is dropped from the package
/// or the schema drifts, these fail instead of the app silently falling back to the 5 samples.
final class ContentLoaderTests: XCTestCase {
    private let shlokas = ContentLoader().load()

    func testLoadsAllShlokas() {
        // 700 traditionally-numbered shlokas + the chapter-13 variant verse (13.0) = 701 records.
        XCTAssertEqual(shlokas.count, 701)
    }

    func testChapter13VariantNumbering() {
        let store = ContentStore(shlokas: shlokas)
        let ch13 = store.shlokas(inChapter: 13)
        // Renumbered so Arjuna's question is 13.0 and the rest keep canonical numbers (13.1…13.34).
        XCTAssertEqual(ch13.map(\.number), Array(0...34))

        let variant = store.shloka(id: "13.0")
        XCTAssertNotNil(variant?.note, "13.0 should carry the textual-variant note")
        XCTAssertEqual(variant?.speaker, "arjuna uvāca")
        XCTAssertTrue(variant?.transliteration.hasPrefix("prakṛtiṁ") ?? false)

        // The traditional opening verse is now 13.1, and it alone has no note.
        let opening = store.shloka(id: "13.1")
        XCTAssertNil(opening?.note)
        XCTAssertEqual(opening?.speaker, "śrī bhagavān uvāca")
        XCTAssertTrue(opening?.transliteration.contains("idaṁ śarīraṁ") ?? false)
    }

    func testOnlyTheVariantVerseHasANote() {
        XCTAssertEqual(shlokas.filter { $0.note != nil }.map(\.id), ["13.0"])
    }

    func testCoversAllEighteenChapters() {
        let chapters = Set(shlokas.map(\.chapter))
        XCTAssertEqual(chapters, Set(1...18))
    }

    func testEveryShlokaHasContent() {
        for s in shlokas {
            XCTAssertFalse(s.transliteration.isEmpty, "\(s.id) has empty transliteration")
            XCTAssertFalse(s.meaning.isEmpty, "\(s.id) has empty meaning")
        }
    }

    func testIDsAreUnique() {
        XCTAssertEqual(Set(shlokas.map(\.id)).count, shlokas.count)
    }

    func testKnownShlokaText() {
        let store = ContentStore(shlokas: shlokas)
        let bg247 = store.shloka(id: "2.47")
        XCTAssertEqual(bg247?.chapter, 2)
        XCTAssertEqual(bg247?.number, 47)
        // Swami Sivananda's translation (the chosen "meaning" — PRD §10.3).
        XCTAssertTrue(
            bg247?.meaning.hasPrefix("Your right is only to work") ?? false,
            "unexpected meaning for 2.47: \(bg247?.meaning ?? "nil")"
        )
        XCTAssertTrue(bg247?.transliteration.contains("karmaṇy") ?? false)
    }

    func testDidNotFallBackToSamples() {
        // The 5-item sample set must never be what ships; catch a missing/broken resource.
        XCTAssertNotEqual(shlokas, ContentStore.sampleShlokas)
    }

    // ── Padapātha / clean-IAST guards (the PDF-sourced transliteration) ──────────────────────────

    func testEveryVerseEndsWithDandaNumber() {
        for s in shlokas {
            XCTAssertNotNil(
                s.transliteration.range(of: #"\|\|\d+\|\|\s*$"#, options: .regularExpression),
                "\(s.id) transliteration should end with a ||N|| marker: \(s.transliteration)"
            )
        }
    }

    func testTransliterationIsCleanIAST() {
        // Legacy display-font cipher glyphs and the old extra-h romanization must never ship.
        let forbidden = ["ä", "¹", "à", "ù", "º", "ç", "é", "ë", "å", "ï", "ü", "ö", "ì", "ò", "è",
                         "kṣh", "śh", "ṛi", "uvācha"]
        for s in shlokas {
            let text = (s.speaker ?? "") + " " + s.transliteration
            for g in forbidden {
                XCTAssertFalse(text.contains(g), "\(s.id) contains forbidden glyph “\(g)”: \(text)")
            }
        }
    }

    func testSpeakerWhenPresentEndsInUvaca() {
        for s in shlokas where s.speaker != nil {
            XCTAssertTrue(s.speaker!.hasSuffix("uvāca"), "\(s.id) speaker is not a ‘… uvāca’ label: \(s.speaker!)")
        }
    }

    func testVerseLinesSplitOnNewlines() {
        // 1.1 is a standard 4-pāda verse.
        let v = ContentStore(shlokas: shlokas).shloka(id: "1.1")
        XCTAssertEqual(v?.verseLines.count, 4)
        XCTAssertEqual(v?.verseLines.first, "dharmakṣetre kurukṣetre")
        XCTAssertTrue(v?.verseLines.last?.hasSuffix("||1||") ?? false)
    }
}
