import Foundation

/// Loads the bundled shloka content into `[Shloka]`.
///
/// The real text — all 701 shlokas with transliteration + Swami Sivananda's English meaning — lives
/// in `gita.json`, a GitaKit package resource generated by `Tools/fetch-content` (impl plan §7
/// Milestone 1, gita-security.md §5). Content is read-only and never CloudKit-synced.
///
/// Views/stores depend on this loader rather than on `ContentStore.sampleShlokas` directly. If the
/// resource is ever missing or unreadable, we fall back to the samples so the shell still renders
/// instead of crashing (matching the launch-safety stance in `DailyGitaApp`).
public struct ContentLoader: Sendable {
    public init() {}

    /// Decode `gita.json` from the given bundle. Pass `nil` (the default) to read GitaKit's own
    /// resource bundle — `Bundle.module` is module-internal, so it can't be a public default value.
    public func load(from bundle: Bundle? = nil) -> [Shloka] {
        let bundle = bundle ?? .module
        guard let url = bundle.url(forResource: "gita", withExtension: "json") else {
            assertionFailure("gita.json not found in bundle — did the package resource get dropped?")
            return ContentStore.sampleShlokas
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode([Shloka].self, from: data)
        } catch {
            assertionFailure("Failed to decode gita.json: \(error)")
            return ContentStore.sampleShlokas
        }
    }
}
